import * as z from "zod"
import * as imports from "../zod-add-schema"

export const products_itemsModel = z.object({
  id: z.number().int(),
  rdate: z.date(),
  valid: z.number().int(),
  cat_id: z.number().int(),
  merchant_id: z.number().int(),
  affiliate_id: z.number().int(),
  title: z.string(),
  text: z.string(),
  url: z.string(),
  cplaccount: z.number(),
  cpi: z.number(),
  cpc: z.number(),
  cpa: z.number(),
  cpllead: z.number(),
  languages: z.string(),
  image: z.string(),
  randomKey: z.string(),
  postbackIPlimit: z.string(),
  param: z.string(),
  productAPICode: z.string(),
  exportUniqueIdWithName: z.string(),
  min_deposit: z.number(),
  terms: z.string(),
  featured: z.number().int(),
  countries_allowed: z.string(),
  terms_and_conditions: z.string(),
  isRTL: z.boolean(),
  type: z.string(),
  ignoreOtherInternalParameters: z.boolean(),
})
